### ISSUE TITLE
Can this tool be used in the command line?

### ISSUE THREAD

**Issue by jafara** [Karetski/Snowonder#11]
And also can the tool automatically format a list of files instead of a single file?

**Comment by Karetski** [comment]
Hi @jafara . The general answer for both questions is no. It's implemented using XcodeKit which doen't give access to the whole project, but only for currently opened file. 

But there is a module of the Snowonder project called ImportArtisan, which is an independent part that is responsible for import declarations processing. I'll think about implementation of command line interface built on top of it. And of course, if you already have such kind of implementation of it feel free to open pull request 😊
