### ISSUE TITLE
OSX10.13

### ISSUE THREAD

**Issue by ghost** [Karetski/Snowonder#22]
can not use in OXS10.13

**Comment by YangXinlei** [comment]
😅

**Comment by Karetski** [comment]
@xianhe92 please give some more context, since I'm currently running it on 10.13.1 with Xcode 9.2 and everything works fine so I can not reproduce the issue

**Comment by ghost** [comment]
@Karetski Thank you, I think it is because I resign my Xcode, could be this reason?

**Comment by ghost** [comment]
@Karetski  I find out, I should use a normal Xcode，thanks!

**Comment by emsihyo** [comment]
@xianhe92 I restored both xcode 9.3 and xcode 9.1 with "update_xcode_plugins --restore",but nothing effected.How can I do?
